name: Deploy to Amazon ECS [blue-green]

on:
  push:
    branches:
      - main
    paths:
      - 'src/hello-world-nodejs/**'

# This is required for GitHub to AWS authentication over OIDC
#permissions:
#  id-token: write # This is required for requesting the JWT
#  contents: read # This is required for actions/checkout

env:
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  DOCKER_IMAGE_TAG: ${{ github.sha }}
  CODEDEPLOY_APPSPEC: .aws/appspec.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-directory: ./src/hello-world-nodejs
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Fetch Amazon ECS task definition
        id: fetch-task-def
        env:
          ECS_TASK_DEFINITION: ${{ vars.ECS_TASK_DEFINITION }}
        run: |
          aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION \
            --query 'taskDefinition' --output json | jq 'del(.compatibilities, .taskDefinitionArn, .requiresAttributes, .revision, .status, .registeredAt, .registeredBy)' > task-def.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECS_TASK_DEFINITION: ${{ steps.fetch-task-def.outputs.task-def }}
          ECS_CONTAINER_NAME: ${{ vars.ECS_CONTAINER_NAME }}
        with:
          task-definition: task-def.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Fill in the new task definition in the Amazon CodeDeploy appspec
        id: appspec
        env:
          CODEDEPLOY_APPSPEC_TASK_DEFINITION: ${{ vars.CODEDEPLOY_APPSPEC_TASK_DEFINITION }}
        run: |
          cat $CODEDEPLOY_APPSPEC \
          | jq --arg key $(aws ecs describe-task-definition --task-definition=$CODEDEPLOY_APPSPEC_TASK_DEFINITION \
          | jq -r '.taskDefinition.taskDefinitionArn') '.Resources[].TargetService.Properties.TaskDefinition=$key' > $CODEDEPLOY_APPSPEC
          cat $CODEDEPLOY_APPSPEC

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        env:
          ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
          ECS_SERVICE: ${{ vars.ECS_SERVICE }}-bg
          CODEDEPLOY_APPLICATION: ${{ vars.CODEDEPLOY_APPLICATION }}
          CODEDEPLOY_DEPLOYMENT_GROUP: ${{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }}
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          codedeploy-appspec: ${{ env.CODEDEPLOY_APPSPEC }}
          codedeploy-application: ${{ env.CODEDEPLOY_APPLICATION }}
          codedeploy-deployment-group: ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }}