name: Run e2e tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # every day at 3am UTC

jobs:
  runner_up:
    uses: ./.github/workflows/runner-scale-up.yaml
    with:
      ECS_SERVICE: gh-actions-dev-gh-runner
      ECS_CLUSTER: gh-actions-dev

  e2e:
    runs-on: self-hosted
    needs: runner_up
    steps:
      - name: Test endpoint
        run: |
          exit 0

  runner_down:
    needs: [runner_up, e2e]
    if: ${{ success() || (failure() && needs.runner_scale_up.result == 'success') }}
    uses: ./.github/workflows/runner-scale-down.yaml
    with:
      ECS_SERVICE: gh-actions-dev-gh-runner
      ECS_CLUSTER: gh-actions-dev